export const enum ClientProt {
    NO_TIMEOUT = 206, // index: 6 - NXT naming

    IDLE_TIMER = 102, // index: 30
    EVENT_TRACKING = 19, // index: 34

    // autogenerated as part of obfuscation process
    ANTICHEAT_OPLOGIC1 = 87, // index: 60
    ANTICHEAT_OPLOGIC2 = 95, // index: 61
    ANTICHEAT_OPLOGIC3 = 146, // index: 62
    ANTICHEAT_OPLOGIC4 = 186, // index: 63
    ANTICHEAT_OPLOGIC5 = 74, // index: 64
    ANTICHEAT_OPLOGIC6 = 250, // index: 65
    ANTICHEAT_OPLOGIC7 = 119, // index: 66
    ANTICHEAT_OPLOGIC8 = 171, // index: 67
    ANTICHEAT_OPLOGIC9 = 233, // index: 68

    // autogenerated as part of obfuscation process
    ANTICHEAT_CYCLELOGIC1 = 136, // index: 70
    ANTICHEAT_CYCLELOGIC2 = 223, // index: 71
    ANTICHEAT_CYCLELOGIC3 = 181, // index: 74
    ANTICHEAT_CYCLELOGIC4 = 94, // index: 72
    ANTICHEAT_CYCLELOGIC5 = 63, // index: 75
    ANTICHEAT_CYCLELOGIC6 = 112, // index: 73

    OPOBJ1 = 113, // index: 80 - NXT naming
    OPOBJ2 = 238, // index: 81 - NXT naming
    OPOBJ3 = 55, // index: 82 - NXT naming
    OPOBJ4 = 17, // index: 83 - NXT naming
    OPOBJ5 = 247, // index: 84 - NXT naming
    OPOBJT = 122, // index: 88 - NXT naming
    OPOBJU = 143, // index: 89 - NXT naming

    OPNPC1 = 180, // index: 100 - NXT naming
    OPNPC2 = 252, // index: 101 - NXT naming
    OPNPC3 = 196, // index: 102 - NXT naming
    OPNPC4 = 107, // index: 103 - NXT naming
    OPNPC5 = 43, // index: 104 - NXT naming
    OPNPCT = 141, // index: 108 - NXT naming
    OPNPCU = 14, // index: 109 - NXT naming

    OPLOC1 = 1, // index: 120 - NXT naming
    OPLOC2 = 219, // index: 121 - NXT naming
    OPLOC3 = 226, // index: 122 - NXT naming
    OPLOC4 = 204, // index: 123 - NXT naming
    OPLOC5 = 86, // index: 124 - NXT naming
    OPLOCT = 208, // index: 128 - NXT naming
    OPLOCU = 147, // index: 129 - NXT naming

    OPPLAYER1 = 135, // index: 140 - NXT naming
    OPPLAYER2 = 165, // index: 141 - NXT naming
    OPPLAYER3 = 172, // index: 142 - NXT naming
    OPPLAYER4 = 54, // index: 143 - NXT naming
    OPPLAYERT = 52, // index: 148 - NXT naming
    OPPLAYERU = 210, // index: 149 - NXT naming

    OPHELD1 = 104, // index: 160 - name based on runescript trigger
    OPHELD2 = 193, // index: 161 - name based on runescript trigger
    OPHELD3 = 115, // index: 162 - name based on runescript trigger
    OPHELD4 = 194, // index: 163 - name based on runescript trigger
    OPHELD5 = 9, // index: 164 - name based on runescript trigger
    OPHELDT = 188, // index: 168 - name based on runescript trigger
    OPHELDU = 126, // index: 169 - name based on runescript trigger

    INV_BUTTON1 = 13, // index: 190 - NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    INV_BUTTON2 = 58, // index: 191 - NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    INV_BUTTON3 = 48, // index: 192 - NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    INV_BUTTON4 = 183, // index: 193 - NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    INV_BUTTON5 = 242, // index: 194 - NXT has "IF_BUTTON5" but for our interface system, this makes more sense

    IF_BUTTON = 177, // index: 200 - NXT naming
    RESUME_PAUSEBUTTON = 239, // index: 201 - NXT naming
    CLOSE_MODAL = 245, // index: 202 - NXT naming
    RESUME_P_COUNTDIALOG = 241, // index: 203 - NXT naming
    TUTORIAL_CLICKSIDE = 243, // index: 204

    MOVE_OPCLICK = 216, // index: 242 - comes with OP packets, name based on other MOVE packets
    REPORT_ABUSE = 205, // index: 243
    MOVE_MINIMAPCLICK = 198, // index: 244 - NXT naming
    INV_BUTTOND = 7, // index: 245 - NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    IGNORELIST_DEL = 4, // index: 246 - NXT naming
    IGNORELIST_ADD = 20, // index: 247 - NXT naming
    IF_PLAYERDESIGN = 150, // index: 248
    CHAT_SETMODE = 8, // index: 249 - NXT naming
    MESSAGE_PRIVATE = 99, // index: 250 - NXT naming
    FRIENDLIST_DEL = 61, // index: 251 - NXT naming
    FRIENDLIST_ADD = 116, // index: 252 - NXT naming
    CLIENT_CHEAT = 11, // index: 253 - NXT naming
    MESSAGE_PUBLIC = 78, // index: 254 - NXT naming
    MOVE_GAMECLICK = 182, // index: 255 - NXT naming
};
